### ISSUE TITLE
Sort out and document our philosophy on what the identify of a node is

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/scuttlebutt#1]
We need a proper single document explaining what a node id identity is.

We have
- the `broadcast_rpc_address`: (using cassandra terminology) the host:port at which other nodes can reach us.
- the `node_id`: defined in the quickwit.yaml file. Today if it is missing we autogenerate it on startup

If specified the `node_id` is something that never changes.  We can add a generation number to disambiguate two different runs.

A couple of problem to consider
- between two runs we probably want to start fresh on the local scuttlebutt state. We don't want other nodes to gossip to us stuff from the past.
- between two runs we want nodes to know that our new stuff is new... Even if they have a version number that is higher.
- node do not know their broadcast_rpc_address .
- we probably want to use the node_id for the cache placement. In other word, there are some benefit to keeping it "sticky". If a node leaves and rejoin, it is a good thing if it takes back its original place in the cache placement logic.

**Comment by evanxg852000** [comment]
> the broadcast_rpc_address: (using cassandra terminology) the host:port at which other nodes can reach us.
@fulmicoton Please, can you clarify, nodes can reach us for what? is this the grpc communication address?
In Cassandra docs it says this is used by clients for cluster metadata, and it looks like a single value for all. But here it's like a value specific to each node.

**Comment by evanxg852000** [comment]
https://www.notion.so/Cluster-Node-Identification-83c2ba2568bc4a199aaf73d04bb98066

**Comment by evanxg852000** [comment]
So the above question has been answered now & noting what I understand from it. 
So the ScuttleButt instance listen-address can be remapped to anything depending on the environment and network. Because of this, a ScuttleButt node has to explicitly advertise the address on which peers can use for message exchange.

**Comment by evanxg852000** [comment]
# Cluster Node Identification

### Context

Given that we have settled with Implementing Quickwit cluster feature using ScuttleButt, We need to clarify what exactly is a cluster node, and what attributes it holds. 

 Couple of issues we want to solve include:

- We want a fresh local scuttlebutt state for every run of a node.
- We don’t want other nodes to override a newly started node state with an obsolete state.
- We want other running nodes to detect that a newly started node’s state prevails all its previous state.
- We want a node to advertise its own gossip address.
- We want a node to have an id that is the same across subsequent runs for keeping cache data around as long as possible.

### What’s needed in ScuttleButt:

- gossip_address:  Address on which to bind for receiving gossip messages via UDP
- gossip_public_adress: Needed for letting other nodes know the address that should be used to contact for exchanging gossip messages. It can have the same value as gossip_address depending on the network environment.
- scuttlebutt_node_id: To uniquely identify a node within the cluster.

*Note: An easy way to make a ScuttleButt node start with a fresh local state without conflicting with the previous state is to start with a new scuttlebutt_node_id.*

### What’s needed in Quickwit:

- quickwit_node_id: To uniquely identify a node within the cluster. Needs to be persistent across multiple runs to avoid invalidating the cache.
- quickwit_node_generation: used to distinguish between subsequent runs of the same node. We can use timestamp (with millisecond precision) just like Apache Cassandra. On each restart, grab the current local timestamp as the node generation value.

### Proposed solution:

By combining the attributes needed, we obtain a node with the following attributes:

```rust
struct Node {
  quickwit_node_id: String, // unic & static from config
  quickwit_node_generation: i64, // timestamp in milliseconds
  gossip_public_address: String, // used for both gossip and as *scuttlebutt_*node_id
}
```

`gossip_public_address` can be used for both gossip and `scuttlebutt_node_id`

`quickwit_node_id` and `quickwit_node_generation`can be set on the node state as key-value pairs. But since these values don’t change while a node is running, we can embed them as part of the  `scuttlebutt_node_id`. 

```rust
scuttlebutt_node_id = {quickwit_node_id}/{gossip_public_address}/{quickwit_node_generation}
```

- `quickwit_node_id`  will be specified via the configuration file
- `gossip_public_address`  will also be specified via the configuration file. We can make it overridable via an environment variable but having support for environment variables interpolation in Quickwit config file would be nice [[Related issue](https://github.com/quickwit-oss/quickwit/issues/1011)]. If not specified in config, it should default to the node ScuttleButt UdpServer address (`gossip_address`). Being able to specify via environment is mostly useful in Kubernetes deployment where one can map [Pod fields to environment variables](https://kubernetes.io/docs/tasks/inject-data-application/_print/#use-pod-fields-as-values-for-environment-variables).

Some benefits of this method are:

- Any change to `quickwit_node_id` or `quickwit_node_generation` will create a new node within the scuttlebutt instance, with a fresh state that cannot conflict with previous states.
- Not caring about the version saves a bit of space from the gossip UDP MTU.
- Keeps the logic of scuttlebutt separate from our particular use case in Quickwit.

### Possible Implementation

```rust
// Inside Scuttlebutt
struct NodeId {
    id: String, // {quickwit_node_id}/{quickwit_node_generation}
    gossip_public_address: SocketAddr,
}

// To allow in NodeState-> BTreeMap<NodeId, VersionedValue>, 
// implements Eq as well
impl Hash for NodeId {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.id.hash(state);
    }
}

// Inside quickwit, we create QuickwitNodeId
struct QuickwitNodeId {
	node_unique_id: String,
    gossip_public_address: String, // advertised UdpServerSocket
    generation: i64, // timestamp (ms) when node started*
}

impl QuickwitNodeId {
    fn new(node_unique_id: String, gossip_public_addres: String) -> Self
	
    fn internal_id(&self) -> String {
		return "{node_unique_id}/{generation}"
	}
}

// parse {node_unique_id}/{generation} into QuickwitNodeId
// useful when we receive membership change event
impl TryFrom<NodeId> for QuickwitNodeId {
    fn try_from(node_id: NodeId) -> Result<Self, Self::Error> {
        parse(node_id.id)?
    }
}

// derive NodeId from QuickwitNodeId
// useful when setting up ScuttleButt instance 
impl From<QuickwitNodeId> for NodeId {
    fn from(node_id: QuickwitNodeId) -> Self {
        Self {
			id: node_id.internale_id(),
		    gossip_public_address: node_id.gossip_public_address,
		}
    }
}

// Example:
let generation = now().as_millis(); 
let quickwit_node = QuickwitNodeId::new(
	"my-happy-node".to_string(), 
	"node-public-ip:8080".parse()?
)
let scuttlebutt_server = ScuttleServer::spawn(
    "localhost:8080".parse()?,
    NodeId::from(quickwit_node),
    ["seed-public-ip:8080".to_string()],
    FailureDetectorConfig::default(),
 );
```

### Potentials Issues:

This solution creates a new node state for every run of a node; leaving the previous state dangling around. This could get out of hand very quickly in environments where nodes are often restarted. However, this issue already exists with the current implementation: When a node permanently leaves the cluster, its state is never cleaned up from the cluster. It would be nice to clean permanently dead nodes [[Related Issue](https://github.com/quickwit-oss/scuttlebutt/issues/17)]. One tradeoff to be aware of is that when a node restarts, it needs to propagate its new state.

### References

- [https://kubernetes.io/docs/tasks/inject-data-application/_print/#pg-c9af1e81bb6e109f6c41febe44f0931b](https://kubernetes.io/docs/tasks/inject-data-application/_print/#pg-c9af1e81bb6e109f6c41febe44f0931b)
